# Generated by Django 5.2.15 on 2026-07-01 05:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="full_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="phone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="preferences",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="appuser",
            name="preferred_channel",
            field=models.TextField(
                choices=[
                    ("in_app", "in_app"),
                    ("sms", "sms"),
                    ("email", "email"),
                    ("whatsapp", "whatsapp"),
                ],
                default="in_app",
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="appuser",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email", ""), _negated=True),
                name="uniq_user_email",
            ),
        ),
    ]
