# Generated by Django 5.2.15 on 2026-07-01 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
        ("catalog", "0001_initial"),
        ("conversations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutreachCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("awaiting_approval", "awaiting_approval"),
                            ("sending", "sending"),
                            ("done", "done"),
                            ("cancelled", "cancelled"),
                        ],
                        default="awaiting_approval",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_campaigns",
                        to="catalog.listing",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "outreach_campaign",
            },
        ),
        migrations.CreateModel(
            name="OutreachRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rank_score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
                ),
                ("rank_reason", models.TextField(blank=True, null=True)),
                ("draft_body", models.TextField(blank=True, null=True)),
                (
                    "channel",
                    models.TextField(
                        choices=[
                            ("in_app", "in_app"),
                            ("sms", "sms"),
                            ("email", "email"),
                            ("whatsapp", "whatsapp"),
                        ],
                        default="in_app",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("pending", "pending"),
                            ("sent", "sent"),
                            ("skipped_already_contacted", "skipped_already_contacted"),
                            ("failed", "failed"),
                            ("cancelled", "cancelled"),
                        ],
                        default="pending",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="outreach.outreachcampaign",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outreach_recipients",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_recipients",
                        to="catalog.listing",
                    ),
                ),
                (
                    "recipient_prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_received",
                        to="buyers.prospect",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outreach_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "outreach_recipient",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("recipient_prospect__isnull", True),
                                ("recipient_user__isnull", False),
                            ),
                            models.Q(
                                ("recipient_prospect__isnull", False),
                                ("recipient_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="outreach_recipient_one_buyer",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("recipient_user__isnull", False), ("status", "sent")),
                        fields=("listing", "recipient_user"),
                        name="uniq_ledger_user",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("recipient_prospect__isnull", False), ("status", "sent")
                        ),
                        fields=("listing", "recipient_prospect"),
                        name="uniq_ledger_prospect",
                    ),
                ],
            },
        ),
    ]
