# Generated by Django 5.2.15 on 2026-07-03 00:34

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.TextField(
                        choices=[("manual", "manual"), ("ai_inferred", "ai_inferred")],
                        default="manual",
                    ),
                ),
                (
                    "strategy",
                    models.TextField(
                        choices=[
                            ("fix_flip", "fix_flip"),
                            ("buy_hold", "buy_hold"),
                            ("brrrr", "brrrr"),
                            ("wholesale", "wholesale"),
                            ("new_construction", "new_construction"),
                        ]
                    ),
                ),
                (
                    "price_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "price_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "arv_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "arv_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("beds_min", models.SmallIntegerField(blank=True, null=True)),
                (
                    "baths_min",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
                ),
                ("sqft_min", models.IntegerField(blank=True, null=True)),
                ("sqft_max", models.IntegerField(blank=True, null=True)),
                ("year_built_min", models.SmallIntegerField(blank=True, null=True)),
                ("lot_size_min", models.IntegerField(blank=True, null=True)),
                (
                    "max_rehab_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "property_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "condition_levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("target_metrics", models.JSONField(blank=True, default=dict)),
                ("funding_type", models.TextField(blank=True, null=True)),
                ("close_days", models.SmallIntegerField(blank=True, null=True)),
                ("notify_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buy_boxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "buy_box",
            },
        ),
        migrations.CreateModel(
            name="BuyBoxGeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "geo_type",
                    models.TextField(
                        choices=[
                            ("state", "state"),
                            ("county", "county"),
                            ("city", "city"),
                            ("zip", "zip"),
                            ("metro", "metro"),
                            ("radius", "radius"),
                            ("polygon", "polygon"),
                        ]
                    ),
                ),
                (
                    "mode",
                    models.TextField(
                        choices=[("include", "include"), ("exclude", "exclude")], default="include"
                    ),
                ),
                ("state_code", models.CharField(blank=True, max_length=2, null=True)),
                ("county_fips", models.CharField(blank=True, max_length=5, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("zip", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "center",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "radius_mi",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "buy_box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geos",
                        to="catalog.buybox",
                    ),
                ),
            ],
            options={
                "db_table": "buy_box_geo",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                (
                    "asking_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "bundle_type",
                    models.TextField(
                        choices=[
                            ("single", "single"),
                            ("package", "package"),
                            ("portfolio", "portfolio"),
                        ],
                        default="single",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("draft", "draft"),
                            ("active", "active"),
                            ("under_contract", "under_contract"),
                            ("paused", "paused"),
                            ("closed", "closed"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="draft",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listing",
            },
        ),
        migrations.CreateModel(
            name="ListingMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[("photo", "photo"), ("document", "document")], default="photo"
                    ),
                ),
                ("url", models.TextField()),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "db_table": "listing_media",
            },
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "floor_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "ceiling_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "must_haves",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("availability_window", models.TextField(blank=True, null=True)),
                ("instructions", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buy_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="catalog.buybox",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "db_table": "mandate",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("apn", models.TextField(blank=True, null=True)),
                ("county_fips", models.CharField(blank=True, max_length=5, null=True)),
                ("address_norm", models.TextField()),
                ("address_raw", models.TextField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("property_type", models.TextField(blank=True, null=True)),
                ("beds", models.SmallIntegerField(blank=True, null=True)),
                (
                    "baths",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
                ),
                ("sqft", models.IntegerField(blank=True, null=True)),
                ("lot_size_sqft", models.IntegerField(blank=True, null=True)),
                ("year_built", models.SmallIntegerField(blank=True, null=True)),
                ("yr_renovated", models.SmallIntegerField(blank=True, null=True)),
                (
                    "floors",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
                ),
                ("sqft_above", models.IntegerField(blank=True, null=True)),
                ("sqft_basement", models.IntegerField(blank=True, null=True)),
                ("condition", models.SmallIntegerField(blank=True, null=True)),
                ("grade", models.SmallIntegerField(blank=True, null=True)),
                ("waterfront", models.BooleanField(blank=True, null=True)),
                ("view_rating", models.SmallIntegerField(blank=True, null=True)),
                (
                    "arv",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "last_sale_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("last_sale_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "property",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("apn__isnull", False)),
                        fields=("county_fips", "apn"),
                        name="uniq_property_parcel",
                    ),
                    models.UniqueConstraint(fields=("address_norm",), name="uniq_property_address"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ListingProperty",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "listing_id",
                        "property_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asking_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("sort_order", models.SmallIntegerField(default=0)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.listing"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.property"
                    ),
                ),
            ],
            options={
                "db_table": "listing_property",
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="properties",
            field=models.ManyToManyField(
                related_name="listings", through="catalog.ListingProperty", to="catalog.property"
            ),
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("property_type", models.TextField(blank=True, null=True)),
                ("beds", models.SmallIntegerField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("state_code", models.CharField(blank=True, max_length=2, null=True)),
                ("zip", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("purchased_at", models.DateField(blank=True, null=True)),
                ("cash_buyer", models.BooleanField(blank=True, null=True)),
                (
                    "disposition",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("flip", "flip"),
                            ("hold", "hold"),
                            ("brrrr", "brrrr"),
                            ("unknown", "unknown"),
                        ],
                        null=True,
                    ),
                ),
                ("source", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="catalog.property",
                    ),
                ),
            ],
            options={
                "db_table": "sale",
            },
        ),
        migrations.AddConstraint(
            model_name="buybox",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("buyer",),
                name="one_primary_box_per_buyer",
            ),
        ),
        migrations.AddIndex(
            model_name="listingmedia",
            index=models.Index(fields=["listing", "sort_order"], name="listing_media_listing_idx"),
        ),
        migrations.AddConstraint(
            model_name="mandate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("buy_box__isnull", True), ("listing__isnull", False)),
                    models.Q(("buy_box__isnull", False), ("listing__isnull", True)),
                    _connector="OR",
                ),
                name="mandate_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="mandate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("listing__isnull", False)),
                fields=("listing",),
                name="uniq_mandate_listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="mandate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("buy_box__isnull", False)),
                fields=("buy_box",),
                name="uniq_mandate_buy_box",
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(fields=["buyer"], name="sale_buyer_idx"),
        ),
    ]
