# Generated by Django 5.2.16 on 2026-07-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingproperty",
            name="baths",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name="listingproperty",
            name="beds",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listingproperty",
            name="condition",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listingproperty",
            name="grade",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listingproperty",
            name="sqft",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listingproperty",
            name="year_built",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listingproperty",
            name="yr_renovated",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
