# Generated by Django 5.2.15 on 2026-07-08 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("chat", "0002_chat_escalated_for"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "stage",
                    models.TextField(
                        choices=[
                            ("contacted", "contacted"),
                            ("engaged", "engaged"),
                            ("negotiating", "negotiating"),
                            ("agreed", "agreed"),
                            ("closed", "closed"),
                            ("lost", "lost"),
                        ],
                        default="contacted",
                    ),
                ),
                ("stage_changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_offer_by_buyer",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "last_offer_by_seller",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "agreed_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals_as_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="chat.chat",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="catalog.listing",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deal",
                "indexes": [
                    models.Index(fields=["seller", "-updated_at"], name="deal_seller_idx"),
                    models.Index(fields=["buyer", "-updated_at"], name="deal_buyer_idx"),
                    models.Index(fields=["chat"], name="deal_chat_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("listing", "buyer"), name="uniq_deal_listing_buyer"
                    )
                ],
            },
        ),
    ]
