# Generated by Django 5.2.15 on 2026-07-03 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pair_key", models.TextField()),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("open", "open"),
                            ("paused", "paused"),
                            ("escalated", "escalated"),
                            ("closed", "closed"),
                        ],
                        default="open",
                    ),
                ),
                (
                    "terminal",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("matched", "matched"),
                            ("no_fit", "no_fit"),
                            ("needs_decision", "needs_decision"),
                        ],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chat",
                "constraints": [
                    models.UniqueConstraint(fields=("pair_key",), name="uniq_chat_pair")
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatMember",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "chat_id",
                        "user_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="chat.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_member",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[("human", "human"), ("agent", "agent"), ("system", "system")]
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("ask", "ask"),
                            ("inform", "inform"),
                            ("qualify", "qualify"),
                            ("hold", "hold"),
                            ("decline", "decline"),
                            ("escalate", "escalate"),
                            ("propose", "propose"),
                            ("counter", "counter"),
                            ("accept", "accept"),
                        ],
                        null=True,
                    ),
                ),
                ("body", models.TextField()),
                ("disclosed_fields", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.TextField(
                        choices=[("draft", "draft"), ("sent", "sent")], default="sent"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("dedup_key", models.TextField(blank=True, null=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.chat",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="chat.message",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
            },
        ),
        migrations.CreateModel(
            name="MessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[("listing", "listing"), ("file", "file"), ("photo", "photo")],
                        default="listing",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_attachments",
                        to="catalog.listing",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="chat.message",
                    ),
                ),
            ],
            options={
                "db_table": "message_attachment",
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["chat", "created_at"], name="chat_message_chat_idx"),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedup_key__isnull", False)),
                fields=("dedup_key",),
                name="uniq_msg_dedup",
            ),
        ),
        migrations.AddIndex(
            model_name="messageattachment",
            index=models.Index(fields=["message", "sort_order"], name="msg_attach_msg_idx"),
        ),
    ]
