# Generated by Django 5.2.15 on 2026-07-01 05:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "asking_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "bundle_type",
                    models.TextField(
                        choices=[
                            ("single", "single"),
                            ("package", "package"),
                            ("portfolio", "portfolio"),
                        ],
                        default="single",
                    ),
                ),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("draft", "draft"),
                            ("active", "active"),
                            ("under_contract", "under_contract"),
                            ("paused", "paused"),
                            ("closed", "closed"),
                            ("withdrawn", "withdrawn"),
                        ],
                        default="draft",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listing",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("apn", models.TextField(blank=True, null=True)),
                ("county_fips", models.CharField(blank=True, max_length=5, null=True)),
                ("address_norm", models.TextField()),
                ("address_raw", models.TextField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("property_type", models.TextField(blank=True, null=True)),
                ("beds", models.SmallIntegerField(blank=True, null=True)),
                (
                    "baths",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
                ),
                ("sqft", models.IntegerField(blank=True, null=True)),
                ("lot_size_sqft", models.IntegerField(blank=True, null=True)),
                ("year_built", models.SmallIntegerField(blank=True, null=True)),
                ("yr_renovated", models.SmallIntegerField(blank=True, null=True)),
                (
                    "floors",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
                ),
                ("sqft_above", models.IntegerField(blank=True, null=True)),
                ("sqft_basement", models.IntegerField(blank=True, null=True)),
                ("condition", models.SmallIntegerField(blank=True, null=True)),
                ("grade", models.SmallIntegerField(blank=True, null=True)),
                ("waterfront", models.BooleanField(blank=True, null=True)),
                ("view_rating", models.SmallIntegerField(blank=True, null=True)),
                (
                    "arv",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "last_sale_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("last_sale_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "property",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("apn__isnull", False)),
                        fields=("county_fips", "apn"),
                        name="uniq_property_parcel",
                    ),
                    models.UniqueConstraint(fields=("address_norm",), name="uniq_property_address"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ListingProperty",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "listing_id",
                        "property_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asking_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.listing"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.property"
                    ),
                ),
            ],
            options={
                "db_table": "listing_property",
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="properties",
            field=models.ManyToManyField(
                related_name="listings", through="catalog.ListingProperty", to="catalog.property"
            ),
        ),
        migrations.CreateModel(
            name="ListingMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.TextField(
                        choices=[("photo", "photo"), ("document", "document")], default="photo"
                    ),
                ),
                ("url", models.TextField()),
                ("sort_order", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "db_table": "listing_media",
                "indexes": [
                    models.Index(fields=["listing", "sort_order"], name="listing_media_listing_idx")
                ],
            },
        ),
    ]
