# Generated by Django 5.2.15 on 2026-07-01 04:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matching", "0001_enable_postgis"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpikePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("geom", django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                "db_table": "spike_point",
            },
        ),
    ]
