# Generated by Django 5.2.15 on 2026-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_outreachcampaign_outreachrecipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="aichat",
            name="pending_confirm",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
