# Generated by Django 5.2.15 on 2026-07-07 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_aichat_pending_confirm"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outreachcampaign",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outreach_campaigns",
                to="catalog.listing",
            ),
        ),
    ]
