# Generated by Django 5.2.15 on 2026-07-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_alter_outreachcampaign_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentactionlog",
            name="action_type",
            field=models.TextField(
                choices=[
                    ("sent", "sent"),
                    ("drafted", "drafted"),
                    ("escalated", "escalated"),
                    ("no_reply", "no_reply"),
                ]
            ),
        ),
    ]
