# Generated by Django 5.2.15 on 2026-07-01 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.TextField(choices=[("thread", "thread"), ("copilot", "copilot")])),
                (
                    "channel",
                    models.TextField(
                        choices=[
                            ("in_app", "in_app"),
                            ("sms", "sms"),
                            ("email", "email"),
                            ("whatsapp", "whatsapp"),
                        ],
                        default="in_app",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("open", "open"),
                            ("paused", "paused"),
                            ("escalated", "escalated"),
                            ("closed", "closed"),
                        ],
                        default="open",
                    ),
                ),
                (
                    "terminal",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("matched", "matched"),
                            ("no_fit", "no_fit"),
                            ("needs_decision", "needs_decision"),
                        ],
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counterparty_prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="buyers.prospect",
                    ),
                ),
                (
                    "counterparty_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counterparty_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="catalog.listing",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copilot_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "conversation",
            },
        ),
        migrations.CreateModel(
            name="ConversationReadState",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "conversation_id",
                        "user_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_read_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="conversations.conversation"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "conversation_read_state",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "author_type",
                    models.TextField(
                        choices=[("human", "human"), ("agent", "agent"), ("system", "system")]
                    ),
                ),
                (
                    "author_side",
                    models.TextField(
                        blank=True, choices=[("seller", "seller"), ("buyer", "buyer")], null=True
                    ),
                ),
                (
                    "action",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("ask", "ask"),
                            ("inform", "inform"),
                            ("qualify", "qualify"),
                            ("hold", "hold"),
                            ("decline", "decline"),
                            ("escalate", "escalate"),
                            ("propose", "propose"),
                            ("counter", "counter"),
                            ("accept", "accept"),
                        ],
                        null=True,
                    ),
                ),
                ("body", models.TextField()),
                ("disclosed_fields", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.TextField(
                        choices=[("draft", "draft"), ("sent", "sent")], default="sent"
                    ),
                ),
                (
                    "channel",
                    models.TextField(
                        choices=[
                            ("in_app", "in_app"),
                            ("sms", "sms"),
                            ("email", "email"),
                            ("whatsapp", "whatsapp"),
                        ],
                        default="in_app",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("dedup_key", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replies",
                        to="conversations.message",
                    ),
                ),
            ],
            options={
                "db_table": "message",
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                condition=models.Q(("kind", "copilot")),
                fields=["owner", "-updated_at"],
                name="copilot_by_owner_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "thread"),
                        ("listing__isnull", False),
                        ("owner__isnull", True),
                        models.Q(
                            models.Q(
                                ("counterparty_prospect__isnull", True),
                                ("counterparty_user__isnull", False),
                            ),
                            models.Q(
                                ("counterparty_prospect__isnull", False),
                                ("counterparty_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("kind", "copilot"),
                        ("owner__isnull", False),
                        ("listing__isnull", True),
                        ("counterparty_user__isnull", True),
                        ("counterparty_prospect__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="conversation_shape",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("counterparty_user__isnull", False)),
                fields=("listing", "counterparty_user"),
                name="uniq_thread_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("counterparty_prospect__isnull", False)),
                fields=("listing", "counterparty_prospect"),
                name="uniq_thread_prospect",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"], name="message_conversation_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dedup_key__isnull", False)),
                fields=("dedup_key",),
                name="uniq_message_dedup",
            ),
        ),
    ]
