# Generated by Django 5.2.15 on 2026-07-01 05:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buyers", "0001_initial"),
        ("catalog", "0001_initial"),
        ("conversations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action_type", models.TextField()),
                ("summary", models.TextField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to="conversations.conversation",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_action_log",
                "indexes": [
                    models.Index(
                        fields=["principal", "-created_at"], name="agent_action_log_princ_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("namespace", models.TextField(default="general")),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_memory",
                "indexes": [
                    models.Index(
                        fields=["principal", "namespace"], name="agent_memory_principal_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "floor_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "ceiling_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "must_haves",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("availability_window", models.TextField(blank=True, null=True)),
                (
                    "autonomy",
                    models.TextField(
                        choices=[
                            ("assist", "assist"),
                            ("confirm_batch", "confirm_batch"),
                            ("auto_with_policy", "auto_with_policy"),
                        ],
                        default="confirm_batch",
                    ),
                ),
                ("auto_reply", models.BooleanField(default=True)),
                ("instructions", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buy_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="buyers.buybox",
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "db_table": "mandate",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("buy_box__isnull", True), ("listing__isnull", False)),
                            models.Q(("buy_box__isnull", False), ("listing__isnull", True)),
                            _connector="OR",
                        ),
                        name="mandate_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("listing__isnull", False)),
                        fields=("listing",),
                        name="uniq_mandate_listing",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("buy_box__isnull", False)),
                        fields=("buy_box",),
                        name="uniq_mandate_buy_box",
                    ),
                ],
            },
        ),
    ]
