# Generated by Django 5.2.15 on 2026-07-01 05:09

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prospect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("full_name", models.TextField(blank=True, null=True)),
                ("entity_name", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("whatsapp", models.TextField(blank=True, null=True)),
                (
                    "preferred_channel",
                    models.TextField(
                        choices=[
                            ("in_app", "in_app"),
                            ("sms", "sms"),
                            ("email", "email"),
                            ("whatsapp", "whatsapp"),
                        ],
                        default="email",
                    ),
                ),
                ("cash_buyer", models.BooleanField(blank=True, null=True)),
                ("signals", models.JSONField(blank=True, default=dict)),
                ("source", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "prospect",
            },
        ),
        migrations.CreateModel(
            name="BuyBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.TextField(
                        choices=[("manual", "manual"), ("ai_inferred", "ai_inferred")],
                        default="manual",
                    ),
                ),
                (
                    "strategy",
                    models.TextField(
                        choices=[
                            ("fix_flip", "fix_flip"),
                            ("buy_hold", "buy_hold"),
                            ("brrrr", "brrrr"),
                            ("wholesale", "wholesale"),
                            ("new_construction", "new_construction"),
                        ]
                    ),
                ),
                (
                    "price_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "price_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "arv_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "arv_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("beds_min", models.SmallIntegerField(blank=True, null=True)),
                (
                    "baths_min",
                    models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
                ),
                ("sqft_min", models.IntegerField(blank=True, null=True)),
                ("sqft_max", models.IntegerField(blank=True, null=True)),
                ("year_built_min", models.SmallIntegerField(blank=True, null=True)),
                ("lot_size_min", models.IntegerField(blank=True, null=True)),
                (
                    "max_rehab_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "property_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                (
                    "condition_levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list, size=None
                    ),
                ),
                ("target_metrics", models.JSONField(blank=True, default=dict)),
                ("funding_type", models.TextField(blank=True, null=True)),
                ("close_days", models.SmallIntegerField(blank=True, null=True)),
                ("notify_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buy_boxes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "buy_box",
            },
        ),
        migrations.CreateModel(
            name="BuyBoxGeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "geo_type",
                    models.TextField(
                        choices=[
                            ("state", "state"),
                            ("county", "county"),
                            ("city", "city"),
                            ("zip", "zip"),
                            ("metro", "metro"),
                            ("radius", "radius"),
                            ("polygon", "polygon"),
                        ]
                    ),
                ),
                (
                    "mode",
                    models.TextField(
                        choices=[("include", "include"), ("exclude", "exclude")], default="include"
                    ),
                ),
                ("state_code", models.CharField(blank=True, max_length=2, null=True)),
                ("county_fips", models.CharField(blank=True, max_length=5, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("zip", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "center",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "radius_mi",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "buy_box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geos",
                        to="buyers.buybox",
                    ),
                ),
            ],
            options={
                "db_table": "buy_box_geo",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("property_type", models.TextField(blank=True, null=True)),
                ("beds", models.SmallIntegerField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("state_code", models.CharField(blank=True, max_length=2, null=True)),
                ("zip", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("purchased_at", models.DateField(blank=True, null=True)),
                ("cash_buyer", models.BooleanField(blank=True, null=True)),
                (
                    "disposition",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("flip", "flip"),
                            ("hold", "hold"),
                            ("brrrr", "brrrr"),
                            ("unknown", "unknown"),
                        ],
                        null=True,
                    ),
                ),
                ("source", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "buyer_prospect",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="buyers.prospect",
                    ),
                ),
                (
                    "buyer_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="catalog.property",
                    ),
                ),
            ],
            options={
                "db_table": "purchase",
            },
        ),
        migrations.AddConstraint(
            model_name="buybox",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("buyer",),
                name="one_primary_box_per_buyer",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("buyer_prospect__isnull", True), ("buyer_user__isnull", False)),
                    models.Q(("buyer_prospect__isnull", False), ("buyer_user__isnull", True)),
                    _connector="OR",
                ),
                name="purchase_one_buyer",
            ),
        ),
    ]
