/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/ai/chats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List / retrieve (with transcript) / delete the user's copilot sessions. */
        get: operations["ai_chats_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chats/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Rehydrate one session. Lazily expire a parked confirm nobody answered first, so a
         *     reopened chat shows a greyed 'expired' card (not a live one) and its composer isn't
         *     gated forever — no background job needed.
         */
        get: operations["ai_chats_retrieve"];
        put?: never;
        post?: never;
        /** @description List / retrieve (with transcript) / delete the user's copilot sessions. */
        delete: operations["ai_chats_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/chats/{id}/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Just the transcript for one session (oldest first). */
        get: operations["ai_chats_messages_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/memory/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The user's durable agent memory (optionally filtered by ?namespace=). */
        get: operations["ai_memory_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/outreach/campaigns/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The seller's outreach campaigns + the ranked shortlist. Approval is the batch-level
         *     send gate: it flips the campaign to `sending` and emits the durable `outreach/approved`
         *     event — a fresh event, not a parked wait, so it survives a closed tab (architecture §6).
         */
        get: operations["ai_outreach_campaigns_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/outreach/campaigns/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The seller's outreach campaigns + the ranked shortlist. Approval is the batch-level
         *     send gate: it flips the campaign to `sending` and emits the durable `outreach/approved`
         *     event — a fresh event, not a parked wait, so it survives a closed tab (architecture §6).
         */
        get: operations["ai_outreach_campaigns_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/outreach/campaigns/{id}/approve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The seller's outreach campaigns + the ranked shortlist. Approval is the batch-level
         *     send gate: it flips the campaign to `sending` and emits the durable `outreach/approved`
         *     event — a fresh event, not a parked wait, so it survives a closed tab (architecture §6).
         */
        post: operations["ai_outreach_campaigns_approve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai/outreach/campaigns/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description The seller's outreach campaigns + the ranked shortlist. Approval is the batch-level
         *     send gate: it flips the campaign to `sending` and emits the durable `outreach/approved`
         *     event — a fresh event, not a parked wait, so it survives a closed tab (architecture §6).
         */
        post: operations["ai_outreach_campaigns_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth_me_partial_update"];
        trace?: never;
    };
    "/api/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Always 200 (never leak account existence); email a signed token iff the
         *     account exists.
         */
        post: operations["auth_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Re-send the verification email. Always 200 (never leak whether an account
         *     exists); a mail is sent only for a real, still-unverified account.
         */
        post: operations["auth_resend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy-boxes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The user's buy-boxes (criteria + inline deal-settings + geos), for `/settings ›
         *     Buy-boxes`. Thin: it validates and delegates to `catalog.services` — the SAME seam the
         *     copilot's buy-box tools call, so the agent and the API stay in lockstep. User-scoped:
         *     a user only ever sees/edits their own boxes (services filters by `buyer_id`; a foreign
         *     id returns an error dict → 404).
         */
        get: operations["buy_boxes_retrieve"];
        put?: never;
        /**
         * @description The user's buy-boxes (criteria + inline deal-settings + geos), for `/settings ›
         *     Buy-boxes`. Thin: it validates and delegates to `catalog.services` — the SAME seam the
         *     copilot's buy-box tools call, so the agent and the API stay in lockstep. User-scoped:
         *     a user only ever sees/edits their own boxes (services filters by `buyer_id`; a foreign
         *     id returns an error dict → 404).
         */
        post: operations["buy_boxes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buy-boxes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description The user's buy-boxes (criteria + inline deal-settings + geos), for `/settings ›
         *     Buy-boxes`. Thin: it validates and delegates to `catalog.services` — the SAME seam the
         *     copilot's buy-box tools call, so the agent and the API stay in lockstep. User-scoped:
         *     a user only ever sees/edits their own boxes (services filters by `buyer_id`; a foreign
         *     id returns an error dict → 404).
         */
        get: operations["buy_boxes_retrieve_2"];
        /**
         * @description The user's buy-boxes (criteria + inline deal-settings + geos), for `/settings ›
         *     Buy-boxes`. Thin: it validates and delegates to `catalog.services` — the SAME seam the
         *     copilot's buy-box tools call, so the agent and the API stay in lockstep. User-scoped:
         *     a user only ever sees/edits their own boxes (services filters by `buyer_id`; a foreign
         *     id returns an error dict → 404).
         */
        put: operations["buy_boxes_update"];
        post?: never;
        /**
         * @description The user's buy-boxes (criteria + inline deal-settings + geos), for `/settings ›
         *     Buy-boxes`. Thin: it validates and delegates to `catalog.services` — the SAME seam the
         *     copilot's buy-box tools call, so the agent and the API stay in lockstep. User-scoped:
         *     a user only ever sees/edits their own boxes (services filters by `buyer_id`; a foreign
         *     id returns an error dict → 404).
         */
        delete: operations["buy_boxes_destroy"];
        options?: never;
        head?: never;
        /**
         * @description The user's buy-boxes (criteria + inline deal-settings + geos), for `/settings ›
         *     Buy-boxes`. Thin: it validates and delegates to `catalog.services` — the SAME seam the
         *     copilot's buy-box tools call, so the agent and the API stay in lockstep. User-scoped:
         *     a user only ever sees/edits their own boxes (services filters by `buyer_id`; a foreign
         *     id returns an error dict → 404).
         */
        patch: operations["buy_boxes_partial_update"];
        trace?: never;
    };
    "/api/buyers/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/buyers/rank?address=…&price=…&beds=…&sqft=…&condition=…&property_type=…
         *     &limit=… — the `/buyers` ad-hoc matcher (no listing persisted). Delegates to the SAME
         *     engine entry point the copilot's `find_buyers` tool uses (agent == API): address→geo
         *     via the known Property universe (no geocoder), then `rank_buyers_for_attrs`. An
         *     unresolvable address degrades to `ranked: []` with `resolved: false`, not an error.
         */
        get: operations["buyers_rank_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chats_retrieve"];
        put?: never;
        /**
         * @description Find-or-create the ONE chat with a counterparty and (optionally) post an
         *     opener with a listing attached. This is the entry point for "Contact seller"
         *     (auto-attaches the listing), "Chat" from /buyers, etc.
         */
        post: operations["chats_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chats_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{id}/approve-draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Approve a `draft_for_approval` agent draft → send it (the takeover). */
        post: operations["chats_approve_draft_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{id}/discard-draft/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Discard a `draft_for_approval` agent draft without sending it (owner-only). */
        post: operations["chats_discard_draft_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{id}/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["chats_messages_retrieve"];
        put?: never;
        post: operations["chats_messages_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chats/{id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["chats_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["deals_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Manual stage override — any stage, any direction (the human corrects the CRM). */
        patch: operations["deals_partial_update"];
        trace?: never;
    };
    "/api/listings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_list"];
        put?: never;
        post: operations["listings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_retrieve"];
        put: operations["listings_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["listings_partial_update"];
        trace?: never;
    };
    "/api/listings/{id}/comps/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_comps_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/mandate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listings_mandate_retrieve"];
        put: operations["listings_mandate_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{id}/valuation/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description On-demand market value + comps for the listing (arv=1 for after-repair). */
        get: operations["listings_valuation_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notifications_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["notifications_read_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["notifications_read_all_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/properties/lookup?address=… → fetch-existing dedup (read-only). */
        get: operations["properties_lookup_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/properties/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/properties/search?q=…&limit=… — closed-world address autocomplete
         *     (typeahead) over the known Property universe. Same service seam as the copilot's
         *     `search_properties` tool (agent == API).
         */
        get: operations["properties_search_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `draft_for_approval` - draft_for_approval
         *     * `auto_send` - auto_send
         * @enum {string}
         */
        AgentAutonomyEnum: "draft_for_approval" | "auto_send";
        AgentMemory: {
            readonly id: number;
            namespace?: string;
            content: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        AiChatDetail: {
            readonly id: number;
            title?: string | null;
            status?: components["schemas"]["Status7eaEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly messages: components["schemas"]["AiMessage"][];
            /**
             * @description The parked write-confirm (`{kind, action, summary, proposal}`) so a reopened
             *     session rebuilds an actionable card; NULL when nothing is awaiting approval.
             */
            readonly pending_confirm: {
                [key: string]: unknown;
            } | null;
        };
        AiChatSummary: {
            readonly id: number;
            title?: string | null;
            status?: components["schemas"]["Status7eaEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        AiMessage: {
            readonly id: number;
            role: components["schemas"]["RoleEnum"];
            content?: string;
            tool_calls?: unknown;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `single` - single
         *     * `package` - package
         *     * `portfolio` - portfolio
         * @enum {string}
         */
        BundleTypeEnum: "single" | "package" | "portfolio";
        Email: {
            /** Format: email */
            email: string;
        };
        /**
         * @description * `photo` - photo
         *     * `document` - document
         * @enum {string}
         */
        KindEnum: "photo" | "document";
        /**
         * @description Create payload: listing fields + a property list (multi-property) + optional
         *     media + optional deal-settings mandate.
         */
        ListingCreate: {
            title?: string;
            description?: string;
            /** Format: decimal */
            asking_price?: string | null;
            /** @default single */
            bundle_type: components["schemas"]["BundleTypeEnum"];
            /** @default active */
            status: components["schemas"]["StatusA30Enum"];
            properties: components["schemas"]["PropertyItem"][];
            media?: components["schemas"]["MediaItem"][];
            mandate?: components["schemas"]["Mandate"];
        };
        /**
         * @description The `/listings/[id]` detail: every property + media + the deal mandate.
         *     Cross-user visible for active listings — the mandate (floor/ceiling/instructions)
         *     is seller-PRIVATE and only serialized for the owner; everyone else gets null.
         */
        ListingDetail: {
            readonly id: number;
            readonly title: string;
            readonly description: string;
            readonly status: components["schemas"]["StatusA30Enum"];
            readonly bundle_type: components["schemas"]["BundleTypeEnum"];
            /** Format: decimal */
            readonly asking_price: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly properties: string;
            readonly media: components["schemas"]["ListingMedia"][];
            readonly mandate: string;
            readonly seller: string;
        };
        ListingMedia: {
            readonly id: number;
            readonly kind: components["schemas"]["KindEnum"];
            readonly url: string;
            readonly sort_order: number;
        };
        /**
         * @description The `/listings` card view: headline fields + primary property + cover photo.
         *     Cross-user visible (marketplace), so it carries the seller's public identity and
         *     nothing seller-private.
         */
        ListingSummary: {
            readonly id: number;
            readonly title: string;
            readonly status: components["schemas"]["StatusA30Enum"];
            readonly bundle_type: components["schemas"]["BundleTypeEnum"];
            /** Format: decimal */
            readonly asking_price: string | null;
            /** Format: date-time */
            readonly created_at: string;
            readonly primary_property: string;
            readonly cover_url: string;
            readonly seller: string;
        };
        ListingUpdate: {
            title?: string;
            description?: string;
            /** Format: decimal */
            asking_price?: string | null;
            bundle_type?: components["schemas"]["BundleTypeEnum"];
            status?: components["schemas"]["StatusA30Enum"];
            mandate?: components["schemas"]["Mandate"];
        };
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description Writable mandate (deal-settings) fields. Target listing is set by the route. */
        Mandate: {
            /** Format: decimal */
            floor_price?: string | null;
            /** Format: decimal */
            ceiling_price?: string | null;
            must_haves?: string[];
            availability_window?: string | null;
            instructions?: string | null;
        };
        MediaItem: {
            /** @default photo */
            kind: components["schemas"]["KindEnum"];
            url: string;
            sort_order?: number;
        };
        Notification: {
            readonly id: number;
            readonly type: components["schemas"]["TypeEnum"];
            readonly chat: number | null;
            readonly payload: unknown;
            /** Format: date-time */
            readonly read_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        OutreachCampaign: {
            readonly id: number;
            readonly listing: number | null;
            /** @description The single-listing display address; NULL for a multi-listing campaign. */
            readonly listing_address: string | null;
            /** @description Distinct addresses across the campaign's recipient rows (multi-listing). */
            readonly listing_addresses: string[];
            readonly copilot_ai_chat: number | null;
            readonly status: components["schemas"]["OutreachCampaignStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            readonly recipients: components["schemas"]["OutreachRecipient"][];
        };
        /**
         * @description * `awaiting_approval` - awaiting_approval
         *     * `sending` - sending
         *     * `done` - done
         *     * `cancelled` - cancelled
         * @enum {string}
         */
        OutreachCampaignStatusEnum: "awaiting_approval" | "sending" | "done" | "cancelled";
        OutreachRecipient: {
            readonly id: number;
            readonly recipient_user: number;
            readonly name: string;
            readonly listing: number;
            readonly listing_address: string | null;
            /** Format: decimal */
            readonly rank_score: string | null;
            readonly rank_reason: string | null;
            readonly draft_body: string | null;
            /** @default pending */
            readonly status: components["schemas"]["OutreachRecipientStatusEnum"];
            readonly chat_id: number;
        };
        /**
         * @description * `pending` - pending
         *     * `sent` - sent
         *     * `skipped_already_contacted` - skipped_already_contacted
         *     * `failed` - failed
         *     * `cancelled` - cancelled
         * @enum {string}
         */
        OutreachRecipientStatusEnum: "pending" | "sent" | "skipped_already_contacted" | "failed" | "cancelled";
        PasswordChange: {
            current_password: string;
            new_password: string;
        };
        PasswordResetConfirm: {
            token: string;
            new_password: string;
        };
        PatchedListingUpdate: {
            title?: string;
            description?: string;
            /** Format: decimal */
            asking_price?: string | null;
            bundle_type?: components["schemas"]["BundleTypeEnum"];
            status?: components["schemas"]["StatusA30Enum"];
            mandate?: components["schemas"]["Mandate"];
        };
        /** @description PATCH the current user's own profile + AI settings (settings page). */
        PatchedProfileUpdate: {
            full_name?: string;
            phone?: string;
            preferred_channel?: components["schemas"]["PreferredChannelEnum"];
            bio?: string;
            company?: string;
            avatar_url?: string;
            preferences?: unknown;
            auto_reply_when_away?: boolean;
            agent_autonomy?: components["schemas"]["AgentAutonomyEnum"];
            agent_reply_cap?: number;
            agent_instructions?: string;
        };
        /**
         * @description * `in_app` - in_app
         *     * `sms` - sms
         *     * `email` - email
         *     * `whatsapp` - whatsapp
         * @enum {string}
         */
        PreferredChannelEnum: "in_app" | "sms" | "email" | "whatsapp";
        Profile: {
            preferences?: unknown;
            bio?: string;
            company?: string;
            avatar_url?: string;
            auto_reply_when_away?: boolean;
            agent_autonomy?: components["schemas"]["AgentAutonomyEnum"];
            agent_reply_cap?: number;
            agent_instructions?: string;
        };
        /** @description One entry in a listing's property list: a match (`property_id`) OR new fields. */
        PropertyItem: {
            property_id?: number | null;
            address?: string;
            property_type?: string | null;
            beds?: number | null;
            /** Format: double */
            baths?: number | null;
            sqft?: number | null;
            lot_size_sqft?: number | null;
            year_built?: number | null;
            condition?: number | null;
            grade?: number | null;
            waterfront?: boolean | null;
            /** Format: decimal */
            asking_price?: string | null;
            sort_order?: number;
        };
        Register: {
            /** Format: email */
            email: string;
            password: string;
            /** @default  */
            full_name: string;
        };
        /**
         * @description * `user` - user
         *     * `assistant` - assistant
         *     * `system` - system
         *     * `tool` - tool
         * @enum {string}
         */
        RoleEnum: "user" | "assistant" | "system" | "tool";
        /**
         * @description * `open` - open
         *     * `archived` - archived
         * @enum {string}
         */
        Status7eaEnum: "open" | "archived";
        /**
         * @description * `draft` - draft
         *     * `active` - active
         *     * `under_contract` - under_contract
         *     * `paused` - paused
         *     * `closed` - closed
         *     * `withdrawn` - withdrawn
         * @enum {string}
         */
        StatusA30Enum: "draft" | "active" | "under_contract" | "paused" | "closed" | "withdrawn";
        Token: {
            token: string;
        };
        /**
         * @description * `inbound_message` - inbound_message
         *     * `outreach_received` - outreach_received
         *     * `approval_required` - approval_required
         *     * `escalation` - escalation
         * @enum {string}
         */
        TypeEnum: "inbound_message" | "outreach_received" | "approval_required" | "escalation";
        /** @description The current user + nested profile (what /api/auth/me returns). */
        User: {
            readonly id: number;
            /** Format: email */
            readonly email: string;
            readonly full_name: string;
            readonly phone: string;
            readonly preferred_channel: components["schemas"]["PreferredChannelEnum"];
            readonly is_email_verified: boolean;
            readonly is_staff: boolean;
            /** Format: date-time */
            readonly date_joined: string;
            readonly profile: components["schemas"]["Profile"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ai_chats_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiChatSummary"][];
                };
            };
        };
    };
    ai_chats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiChatDetail"];
                };
            };
        };
    };
    ai_chats_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ai_chats_messages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiChatSummary"];
                };
            };
        };
    };
    ai_memory_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentMemory"][];
                };
            };
        };
    };
    ai_outreach_campaigns_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachCampaign"][];
                };
            };
        };
    };
    ai_outreach_campaigns_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachCampaign"];
                };
            };
        };
    };
    ai_outreach_campaigns_approve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OutreachCampaign"];
                "application/x-www-form-urlencoded": components["schemas"]["OutreachCampaign"];
                "multipart/form-data": components["schemas"]["OutreachCampaign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachCampaign"];
                };
            };
        };
    };
    ai_outreach_campaigns_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["OutreachCampaign"];
                "application/x-www-form-urlencoded": components["schemas"]["OutreachCampaign"];
                "multipart/form-data": components["schemas"]["OutreachCampaign"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutreachCampaign"];
                };
            };
        };
    };
    auth_csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProfileUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileUpdate"];
                "multipart/form-data": components["schemas"]["PatchedProfileUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
                "multipart/form-data": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Email"];
                "application/x-www-form-urlencoded": components["schemas"]["Email"];
                "multipart/form-data": components["schemas"]["Email"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            /** @description No response body */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_resend_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Email"];
                "application/x-www-form-urlencoded": components["schemas"]["Email"];
                "multipart/form-data": components["schemas"]["Email"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Token"];
                "application/x-www-form-urlencoded": components["schemas"]["Token"];
                "multipart/form-data": components["schemas"]["Token"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buy_boxes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buy_boxes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buy_boxes_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buy_boxes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buy_boxes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buy_boxes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    buyers_rank_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chats_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chats_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chats_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chats_approve_draft_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chats_discard_draft_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chats_messages_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chats_messages_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    chats_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deals_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deals_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    listings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingSummary"][];
                };
            };
        };
    };
    listings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["ListingCreate"];
                "multipart/form-data": components["schemas"]["ListingCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingCreate"];
                };
            };
        };
    };
    listings_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
        };
    };
    listings_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ListingUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["ListingUpdate"];
                "multipart/form-data": components["schemas"]["ListingUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingUpdate"];
                };
            };
        };
    };
    listings_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedListingUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedListingUpdate"];
                "multipart/form-data": components["schemas"]["PatchedListingUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingUpdate"];
                };
            };
        };
    };
    listings_comps_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
        };
    };
    listings_mandate_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
        };
    };
    listings_mandate_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ListingDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["ListingDetail"];
                "multipart/form-data": components["schemas"]["ListingDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
        };
    };
    listings_valuation_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingDetail"];
                };
            };
        };
    };
    notifications_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
        };
    };
    notifications_read_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this notification. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    notifications_read_all_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Notification"];
                "application/x-www-form-urlencoded": components["schemas"]["Notification"];
                "multipart/form-data": components["schemas"]["Notification"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
        };
    };
    properties_lookup_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    properties_search_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
