# Generated by Django 5.2.15 on 2026-07-08 04:44

from django.db import migrations, models


def _raise_default_cap(apps, schema_editor):
    """Rows still at the old default (3) move to the new default (6). Caveat: a user
    who deliberately chose 3 moves too — indistinguishable, accepted (plan 2026-07-08)."""
    UserProfile = apps.get_model("users", "UserProfile")
    UserProfile.objects.filter(agent_reply_cap=3).update(agent_reply_cap=6)


def _noop(apps, schema_editor):
    pass  # reverse: keep 6 — no way to know who was migrated vs chose it


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_agent_autonomy_auto_send"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="agent_reply_cap",
            field=models.PositiveSmallIntegerField(default=6),
        ),
        migrations.RunPython(_raise_default_cap, _noop),
    ]
